name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: transformation des fichiers php
        run: | 
           mv index.html  index.php
           mv gift.html  gift.php
            
      - name: upload FTP
        uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
        with:
          host: ftp.cluster021.hosting.ovh.net
          user: potametrck
          password:  ${{ secrets.FTP_PASSWORD }}
          remoteDir: www
  
