name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: transformation des fichiers php
        run: | 
           cd src
           mv index.html  index.php
           mv gift.html  gift.php
           mv navette.html  navette.php
            
      - name: install tooling
        run: |
          npm install uglify-js -g
          npm install clean-css -g

      - name: compressing
        run: |
          cd src
          uglifyjs js/bootstrap/bootstrap.js > js/bootstrap/bootstrap.min.js
          uglifyjs js/flexslider/jquery.flexslider.js > js/flexslider/jquery.flexslider.min.js
          uglifyjs js/bootstrap/bootstrap.js > js/bootstrap/bootstrap.min.js
          

      - name: upload FTP
        uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
        with:
          host: ftp.cluster021.hosting.ovh.net
          user: potametrck
          password:  ${{ secrets.FTP_PASSWORD }}
          remoteDir: www
          localDir: src
  
